/**
 * Central type exports for ARCS frontend.
 */

// Common types
export type {
  Vector3,
  Quaternion,
  Matrix4x4,
  SE3Pose,
  Range,
  WorkspaceBounds,
  JointState,
  Timestamp,
  UUID,
  AsyncStatus,
  ConnectionState,
  Nullable,
  NumericArray,
  DeviceType,
  FilePath,
} from './common';

// API types
export type {
  ApiResponse,
  ApiMeta,
  ApiError,
  PaginatedResponse,
  PaginationMeta,
  PaginationParams,
  SortDirection,
  SortParams,
  FilterOperator,
  FilterCondition,
  HttpMethod,
  RequestOptions,
  RetryOptions,
  ApiClientConfig,
  WebSocketMessageType,
  WebSocketMessage,
  SubscribeMessage,
  UnsubscribeMessage,
  HealthCheckResponse,
  ServiceHealth,
} from './api';

// Simulation types
export type {
  SimulationBackend,
  SimulationTask,
  SimulationStatus,
  SimulationConfig,
  SimulationSession,
  Observation,
  SimulationState,
  StepRequest,
  StepResponse,
  StepInfo,
  ResetRequest,
  ObservationResponse,
  StateResponse,
  RenderConfig,
  RenderedFrame,
  EnvironmentInfo,
  SpaceInfo,
  BatchStepRequest,
  BatchStepResponse,
} from './simulation';

// Training types
export type {
  Algorithm,
  TrainingStatus,
  PPOConfig,
  SACConfig,
  TD3Config,
  NetworkConfig,
  TrainingConfig,
  StartTrainingRequest,
  TrainingRun,
  TrainingMetrics,
  TrainingStats,
  Checkpoint,
  EvaluationResult,
  EpisodeSummary,
  HyperparameterSearchConfig,
  SearchSpace,
  TrialResult,
  LearningCurvePoint,
  CallbackConfig,
  EarlyStoppingConfig,
  ExperimentLoggerConfig,
} from './training';

// Kinematics types
export type {
  FKRequest,
  FKResponse,
  IKRequest,
  IKResponse,
  JacobianRequest,
  JacobianResponse,
  JointLimit,
  JointLimitsResponse,
  JointLimitCheckRequest,
  JointViolation,
  JointLimitCheckResponse,
  VelocityKinematicsRequest,
  VelocityKinematicsResponse,
  DifferentialIKRequest,
  DifferentialIKResponse,
  ManipulabilityRequest,
  ManipulabilityResponse,
  PathSegmentType,
  CartesianPathSegment,
  CartesianPathRequest,
  CartesianPathResponse,
  CollisionCheckRequest,
  Obstacle,
  CollisionCheckResponse,
  CollisionPair,
  URDFInfo,
  DHParameter,
  ChainInfo,
} from './kinematics';

// Robot types
export type {
  ControlMode,
  GripperState,
  RobotConnectionStatus,
  RobotArmState,
  JointLimits,
  RobotConfig,
  RobotInfo,
  JointPositionCommand,
  JointVelocityCommand,
  JointTorqueCommand,
  CartesianPoseCommand,
  ImpedanceParams,
  ImpedanceCommand,
  GripperCommand,
  MotionCommand,
  RobotError,
  RobotStatusUpdate,
  RobotTelemetry,
  SafetyStatus,
  TrajectoryPoint,
  JointTrajectory,
  TrajectoryStatus,
  TrajectoryResult,
  TeachModeConfig,
  Workspace,
  DigitalIO,
  AnalogIO,
  ToolConfig,
  PayloadEstimation,
} from './robot';

// Dataset types
export type {
  DatasetFormat,
  DatasetSummary,
  DatasetListResponse,
  DatasetStatistics,
  Demonstration,
  DemonstrationMetadata,
  DemonstrationResponse,
  FilterOptions,
  AugmentationOptions,
  ProcessDatasetRequest,
  DatasetConfig,
  RecordingSession,
  RecordingCommand,
  Transition,
  TransitionBatch,
  ReplayBufferInfo,
  DatasetSplitConfig,
  DatasetSplitResult,
  DataLoaderConfig,
  DatasetMergeRequest,
  DatasetExportRequest,
  DatasetImportRequest,
  DatasetValidationResult,
  ValidationError,
  ValidationWarning,
} from './dataset';

// Safety types
export type {
  SafetyJointLimits,
  SafetyConfig,
  SafetyFilterRequest,
  SafetyFilterResponse,
  SafetyStatusResponse,
  SafetyViolation,
  SafetyViolationType,
  SafetyEvent,
  SafetyEventType,
  CollisionConfig,
  ForceTorqueLimits,
  PowerForceLimitingConfig,
  SafetyZone,
  SafetyZoneGeometry,
  SpeedSeparationConfig,
  SafetyStats,
  SafetyAuditEntry,
  EmergencyStopState,
  SafetySystemHealth,
  CompliantMotionConfig,
  RecoveryAction,
  SafetyInterlock,
} from './safety';
